### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by Zazo032**

### CODE REVIEW

**Comment by Zazo032** [comment]
@jasonlewicki could you review this changes? To make the plugin compatible with latest Flutter and Android versions

**Comment by samuelchanx** [comment]
This is needed for me too. Currently this breaks the app from compiling with following errors:

```
           FAILURE: Build failed with an exception.

           * Where:
           Build file '/Users/SC/flutter/.pub-cache/git/flutter_stetho-08ce9fd760ce5ab4a41e162d59e1c422bc5eda74/android/build.gradle' line: 19

           * What went wrong:
           A problem occurred evaluating root project 'flutter_stetho'.
           > Failed to apply plugin [id 'com.android.library']
              > Minimum supported Gradle version is 5.4.1. Current version is 4.1. If using the gradle wrapper, try editing the distributionUrl in /Users/SC/flutter/.pub-cache/git/flutter_stetho-08ce9fd760ce5ab4a41e162d59e1c422bc5eda74/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by jasonlewicki** [comment]
@Zazo032 @samuelchanx: I'll take a look tonight.

**Review by jasonlewicki — APPROVED** [review]

**Comment by jasonlewicki** [comment]
@Zazo032 @samuelchanx Merged.

**Pull request merged**
